### ISSUE TITLE
Not Enough Values to Unpack - group_notes_with_same_edge

### ISSUE THREAD

**Issue by jymbcrc** [xomicsdatascience/CsoDIAq#20]
[CsoDIAq-file1_20210222_DISPA_hela_03_corrected.csv](https://github.com/CCranney/CsoDIAq/files/7945800/CsoDIAq-file1_20210222_DISPA_hela_03_corrected.csv)

the raw data was converted as below:
![image](https://user-images.githubusercontent.com/96434559/151252746-bf7fbd4e-bc45-408b-89fa-61a432efc449.png)

after processing by CSODIAQ the Maccscore is 0

**Comment by jessegmeyerlab** [comment]
@jymbcrc can you please also share the last output in the csoDIAq console that looked like an error message?

**Comment by jessegmeyerlab** [comment]
@jymbcrc actually maybe just copy the whole output into a text file and add here?

**Comment by jessegmeyerlab** [comment]
@CCranney I am getting the same problem when I try to run csoDIAq on our same file from before - here is the full console output
[error_test_from_jesse.txt](https://github.com/CCranney/CsoDIAq/files/7946123/error_test_from_jesse.txt)
 
I suspect a problem with a new package version? do you still have the original version of csodiaq install you made months ago that you can test Yuming's file with?

**Comment by jessegmeyerlab** [comment]
BTW @CCranney - Yuming Jiang @jymbcrc is a new postdoc in the lab working on DISPA

**Comment by CCranney** [comment]
Migrating other comments to here.

Data:
[data.zip](https://github.com/CCranney/CsoDIAq/files/7955140/data.zip)

Output:
[error_text_jymbcrc.txt](https://github.com/CCranney/CsoDIAq/files/7955151/error_text_jymbcrc.txt)

**Comment by CCranney** [comment]
Hi @jessegmeyerlab  and @jymbcrc,

I'm looking over the problem now. Based on the output I assume this is for the "Peptide/Protein Quantification" tab on the GUI - can I get a screenshot of your settings and access to the library file used? I believe the data file above is specifically the DIA data file. I switched computers a couple months ago and am having a hard time tracking down files from this project.

Also, I'm comparing your error outputs - I'm seeing a different final error between the two. Jesse's output ends with:

>   File "C:\Users\jesse\AppData\Roaming\Python\Python37\site-packages\idpicker.py", line 23, in group_nodes_with_same_edge
>     if first: l1, l2 = map(list,zip(*data))
> ValueError: not enough values to unpack (expected 2, got 0)

Whereas YuMing's data ends with a deprecation error, a benign error suggesting that the program went to completion. I seem to recall investigating this error and determining that it wouldn't be a problem in the future, though my recollection is fuzzy. 

I renamed the issue to tackle the error I saw in Jesse's output - let me know if I'm reading any of that incorrectly.

**Comment by jessegmeyerlab** [comment]
Thanks for looking at this Caleb. I used the default settings except I clicked the "protein inference" checkbox. I used the human.tsv library you put on zenodo. I didn't notice Yuming's error is different, but we both got empty output

**Comment by jessegmeyerlab** [comment]
And no this was for the first tab the peptide protein identification

**Comment by jessegmeyerlab** [comment]
I'm curious if you can get through the default protein identification with CsoDIAq with that file and that library

**Comment by jessegmeyerlab** [comment]
Let me know if I missed any questions

**Comment by jessegmeyerlab** [comment]
for reference this is the file that got us over 1000 proteins when we were testing your program last February 2021

**Comment by CCranney** [comment]
Sounds good! I've downloaded the library file, but ran into a problem with the data file. I'm forgetting, how should I convert it from a .raw format to .mzXML? Also, I'm not seeing the DISPA data files on zenodo - was that an oversight we should correct, an intentional omission, or am I just not finding it?

**Comment by jessegmeyerlab** [comment]
Here is the converted version we used to save you the time. Just so you know how the data conversion from RAW is done with msconvertgui which is part of proteowizard using the settings in Yumings first post above.
[20210222_DISPA_hela_03.zip](https://github.com/CCranney/CsoDIAq/files/7955481/20210222_DISPA_hela_03.zip)
 

There should not be DISPA data on zenodo no

**Comment by CCranney** [comment]
Hm... I'm getting output from those data files. This may be a Windows/Mac thing, though I'm not sure how or why that would be. Can you confirm all of the below settings are set appropriately?

<img width="646" alt="Screen Shot 2022-01-27 at 9 10 35 PM" src="https://user-images.githubusercontent.com/11773171/151485964-81a66fcc-cc24-4bab-b36d-6639290993d7.png">

My output:
[temp_delete.zip](https://github.com/CCranney/CsoDIAq/files/7955608/temp_delete.zip)

For reference, it looks like the error @jessegmeyerlab encountered occurs while processing proteins, and will likely not occur if the Protein Inference box is not checked.

**Comment by jessegmeyerlab** [comment]
Hi Caleb,

Yes those are the settings I used. It could be windows versus mac. I can try installing on my wife's mac later today and let you know. 

Did you do a fresh install or is this the version you already had installed? 

We both had trouble getting it installed so it could also be a package version or install issue. 

Yes it does look like the error is while trying to infer proteins, but I looked in the spectra and peptide outputs and they are empty so I think that is why it fails at protein inference. I'm attaching all of the outputs that it makes before it runs into this error. You can see that there are hits in the "corrected" file but the MaCC score and cosine scores are both zero.
[20220126_test.zip](https://github.com/CCranney/CsoDIAq/files/7958925/20220126_test.zip)
.

**Comment by CCranney** [comment]
Mine was a fresh install. Did you do it in a new conda environment? It may be that several package versions pre-downloaded on the computer do not match what CsoDIAq requires.

And sounds good, let me know if anything changes on your wife's mac!

**Comment by jessegmeyerlab** [comment]
I can try it in a new conda environment right now good idea - do I have to uninstall the old version?

**Comment by jessegmeyerlab** [comment]
what python version do you use?

**Comment by CCranney** [comment]
I don't think you need to uninstall the old version, but you may want to try if the same problem occurs in a new conda environment. My current computer is using python 3.9.7.

**Comment by jessegmeyerlab** [comment]
It worked! Must be a problem with the installation. I will update the instructions now in the wiki and ask @jymbcrc to try them and see if its fixed for him too. Sorry to both you with this and thanks so much for your help! I actually get almost 1500 protein groups with this analysis 0.0

**Comment by jessegmeyerlab** [comment]
@jymbcrc can you try the updated installation instructions and see if that fixes this for you? Find the instructions here:
https://github.com/CCranney/CsoDIAq/wiki/Install-Instructions-for-Windows

**Comment by CCranney** [comment]
No further comments on this issue, assuming it's fixed. Closing.
