### ISSUE TITLE
the whole text from the console for the MaCCscore=0

### ISSUE THREAD

**Issue by jymbcrc** [xomicsdatascience/CsoDIAq#23]
Executing process
Enter library dictionary upload: 
0:00:12.152381

Begin Grouping Scans by m/z Windows:
0:00:30.902689

Number of Unpooled MS/MS Query Spectra: 2459
Number of Pooled MS/MS Query Spectra/Mz Windows: 400

Begin Pooled Spectra Analysis:
0:00:31.938786

Number of Pooled Experimental Spectra Analyzed: 10
Number of Spectra in Current Pooled Spectra: 7
Time Since Last Checkpoint: 1.76 Seconds

Number of Pooled Experimental Spectra Analyzed: 20
Number of Spectra in Current Pooled Spectra: 7
Time Since Last Checkpoint: 0.32 Seconds

Number of Pooled Experimental Spectra Analyzed: 30
Number of Spectra in Current Pooled Spectra: 7
Time Since Last Checkpoint: 0.37 Seconds

Number of Pooled Experimental Spectra Analyzed: 40
Number of Spectra in Current Pooled Spectra: 7
Time Since Last Checkpoint: 0.63 Seconds

Number of Pooled Experimental Spectra Analyzed: 50
Number of Spectra in Current Pooled Spectra: 7
Time Since Last Checkpoint: 0.44 Seconds

Number of Pooled Experimental Spectra Analyzed: 60
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.49 Seconds

Number of Pooled Experimental Spectra Analyzed: 70
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.54 Seconds

Number of Pooled Experimental Spectra Analyzed: 80
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.55 Seconds

Number of Pooled Experimental Spectra Analyzed: 90
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.87 Seconds

Number of Pooled Experimental Spectra Analyzed: 100
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.65 Seconds

Number of Pooled Experimental Spectra Analyzed: 110
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.67 Seconds

Number of Pooled Experimental Spectra Analyzed: 120
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.92 Seconds

Number of Pooled Experimental Spectra Analyzed: 130
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.7 Seconds

Number of Pooled Experimental Spectra Analyzed: 140
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.7 Seconds

Number of Pooled Experimental Spectra Analyzed: 150
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.92 Seconds

Number of Pooled Experimental Spectra Analyzed: 160
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.69 Seconds

Number of Pooled Experimental Spectra Analyzed: 170
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.89 Seconds

Number of Pooled Experimental Spectra Analyzed: 180
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.66 Seconds

Number of Pooled Experimental Spectra Analyzed: 190
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.66 Seconds

Number of Pooled Experimental Spectra Analyzed: 200
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.63 Seconds

Number of Pooled Experimental Spectra Analyzed: 210
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.79 Seconds

Number of Pooled Experimental Spectra Analyzed: 220
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.59 Seconds

Number of Pooled Experimental Spectra Analyzed: 230
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.58 Seconds

Number of Pooled Experimental Spectra Analyzed: 240
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.54 Seconds

Number of Pooled Experimental Spectra Analyzed: 250
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.77 Seconds

Number of Pooled Experimental Spectra Analyzed: 260
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.56 Seconds

Number of Pooled Experimental Spectra Analyzed: 270
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.52 Seconds

Number of Pooled Experimental Spectra Analyzed: 280
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.5 Seconds

Number of Pooled Experimental Spectra Analyzed: 290
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.53 Seconds

Number of Pooled Experimental Spectra Analyzed: 300
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.69 Seconds

Number of Pooled Experimental Spectra Analyzed: 310
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.45 Seconds

Number of Pooled Experimental Spectra Analyzed: 320
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.43 Seconds

Number of Pooled Experimental Spectra Analyzed: 330
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.41 Seconds

Number of Pooled Experimental Spectra Analyzed: 340
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.42 Seconds

Number of Pooled Experimental Spectra Analyzed: 350
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.4 Seconds

Number of Pooled Experimental Spectra Analyzed: 360
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.36 Seconds

Number of Pooled Experimental Spectra Analyzed: 370
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.34 Seconds

Number of Pooled Experimental Spectra Analyzed: 380
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.33 Seconds

Number of Pooled Experimental Spectra Analyzed: 390
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.33 Seconds

Number of Pooled Experimental Spectra Analyzed: 400
Number of Spectra in Current Pooled Spectra: 6
Time Since Last Checkpoint: 0.3 Seconds
Begin FDR Analysis:
0:00:55.858695

Begin Correction Process:
0:00:56.125352

Begin Corrected FDR Analysis:
0:00:56.653411

Begin Writing to File: 
0:00:57.151637

Generating FDR Analysis Files:
0:00:57.384080

Generate DISPA Targeted Reanalysis Files:
0:00:57.462499

C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'libIntensities' of function 'find_matching_peaks'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\spectra_matcher_functions.py", line 15:[0m
[1m@njit
[1mdef find_matching_peaks(libMzs, libIntensities, libTags, queMzs, queIntensities, queTags, ppmTol):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'libMzs' of function 'find_matching_peaks'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\spectra_matcher_functions.py", line 15:[0m
[1m@njit
[1mdef find_matching_peaks(libMzs, libIntensities, libTags, queMzs, queIntensities, queTags, ppmTol):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'libTags' of function 'find_matching_peaks'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\spectra_matcher_functions.py", line 15:[0m
[1m@njit
[1mdef find_matching_peaks(libMzs, libIntensities, libTags, queMzs, queIntensities, queTags, ppmTol):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'queIntensities' of function 'find_matching_peaks'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\spectra_matcher_functions.py", line 15:[0m
[1m@njit
[1mdef find_matching_peaks(libMzs, libIntensities, libTags, queMzs, queIntensities, queTags, ppmTol):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'queMzs' of function 'find_matching_peaks'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\spectra_matcher_functions.py", line 15:[0m
[1m@njit
[1mdef find_matching_peaks(libMzs, libIntensities, libTags, queMzs, queIntensities, queTags, ppmTol):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'queTags' of function 'find_matching_peaks'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\spectra_matcher_functions.py", line 15:[0m
[1m@njit
[1mdef find_matching_peaks(libMzs, libIntensities, libTags, queMzs, queIntensities, queTags, ppmTol):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\Users\yujiang\AppData\Roaming\Python\Python38\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: [1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'maccScores' of function 'reduce_duplicate_rows'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
[1m
File "..\..\programdata\anaconda3\lib\site-packages\IdentificationSpectraMatcher.py", line 73:[0m
[1m@njit
[1mdef reduce_duplicate_rows(matchLibTags, matchQueTags, maccScores, decoys):
[0m[1m^[0m[0m
[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))

Process finished.

**Comment by CCranney** [comment]
Merged with another issue (see [here](https://github.com/CCranney/CsoDIAq/issues/20))
