### ISSUE TITLE
idpicker/find_valid_proteins returns different ordering across repetition

### ISSUE THREAD

**Issue by AlexandreHutton** [xomicsdatascience/CsoDIAq#44]
The function `find_valid_proteins` returns values in a different order when run multiple times with the same settings. This causes the `_proteinFDR.csv` and `_allCVs.csv` files to have different orderings in the `leadingProtein` column and nowhere else.

**Comment by CCranney** [comment]
Made a fix for what I believe is the issue described, see the above PR.
